# Hierarchical Optimization Rules for Enhanced Memory Bank MCP
# Regras carregadas hierarquicamente por modo e complexidade

global:
  # Regras sempre carregadas
  base_memory_optimization: true
  token_limit_target: 8000
  lazy_loading: true
  context_caching: true

modes:
  VAN:
    description: "Visualização e análise inicial"
    token_target: 2000
    rules:
      - van-core
      - memory-structure
      - project-mapping
    level_rules:
      1: ["van-quick", "basic-analysis"]
      2: ["van-standard", "detailed-mapping"]
      3: ["van-comprehensive", "full-analysis"]
      4: ["van-expert", "deep-insights"]

  PLAN:
    description: "Planejamento detalhado"
    token_target: 3000
    rules:
      - plan-core
      - task-breakdown
      - dependency-mapping
    level_rules:
      1: ["plan-simple", "basic-tasks"]
      2: ["plan-structured", "detailed-breakdown"]
      3: ["plan-comprehensive", "full-planning"]
      4: ["plan-expert", "advanced-strategies"]

  CREATIVE:
    description: "Decisões de design e arquitetura"
    token_target: 4000
    rules:
      - creative-core
      - design-patterns
      - architecture-guidelines
    level_rules:
      1: ["creative-quick", "simple-decisions"]
      2: ["creative-analysis", "option-comparison"]
      3: ["creative-detailed", "comprehensive-design"]
      4: ["creative-expert", "architectural-mastery"]

  IMPLEMENT:
    description: "Implementação e desenvolvimento"
    token_target: 3500
    rules:
      - implement-core
      - code-patterns
      - best-practices
    level_rules:
      1: ["implement-basic", "simple-coding"]
      2: ["implement-standard", "structured-development"]
      3: ["implement-advanced", "complex-solutions"]
      4: ["implement-expert", "optimized-patterns"]

  QA:
    description: "Quality Assurance e validação"
    token_target: 2500
    rules:
      - qa-core
      - testing-strategies
      - validation-patterns
    level_rules:
      1: ["qa-basic", "simple-tests"]
      2: ["qa-standard", "comprehensive-testing"]
      3: ["qa-advanced", "integration-testing"]
      4: ["qa-expert", "performance-validation"]

  REFLECT:
    description: "Reflexão e documentação"
    token_target: 2000
    rules:
      - reflect-core
      - documentation-patterns
      - learning-capture
    level_rules:
      1: ["reflect-quick", "basic-notes"]
      2: ["reflect-standard", "detailed-documentation"]
      3: ["reflect-comprehensive", "full-analysis"]
      4: ["reflect-expert", "strategic-insights"]

  ARCHIVE:
    description: "Arquivamento e consolidação"
    token_target: 1500
    rules:
      - archive-core
      - consolidation-patterns
      - knowledge-management
    level_rules:
      1: ["archive-basic", "simple-storage"]
      2: ["archive-standard", "organized-archival"]
      3: ["archive-comprehensive", "full-documentation"]
      4: ["archive-expert", "knowledge-base"]

# Otimizações específicas por complexidade
complexity_optimizations:
  1:
    description: "Tarefas simples e diretas"
    max_tokens: 2000
    optimizations:
      - compact-templates
      - essential-context-only
      - streamlined-workflows
  
  2:
    description: "Tarefas estruturadas"
    max_tokens: 4000
    optimizations:
      - structured-templates
      - focused-context
      - balanced-workflows
  
  3:
    description: "Tarefas complexas"
    max_tokens: 6000
    optimizations:
      - detailed-templates
      - comprehensive-context
      - full-workflows
  
  4:
    description: "Tarefas de especialista"
    max_tokens: 8000
    optimizations:
      - expert-templates
      - complete-context
      - advanced-workflows

# Templates progressivos por token target
templates:
  token_targets:
    compact: 200    # Level 1
    standard: 500   # Level 2
    detailed: 1000  # Level 3
    comprehensive: 2000 # Level 4

# Caching strategies
caching:
  context_cache_duration: 3600  # 1 hora
  rule_cache_duration: 7200     # 2 horas
  template_cache_duration: 86400 # 24 horas
  
# Performance monitoring
monitoring:
  track_token_usage: true
  track_rule_loading_time: true
  track_template_rendering_time: true
  log_optimization_effectiveness: true